In [1]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("book1-100k.csv")
df1["Pages"] = df1["pagesNumber"]
df_books = df1.drop(['RatingDist1', 'RatingDist2', 'RatingDist3', 'RatingDist4', 'RatingDist5', "pagesNumber"], axis=1)
df_books.head()

,Id,Name,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,ISBN,Pages
0,1,Harry Potter and the Half-Blood Prince (Harry ...,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,NaN,652
1,2,Harry Potter and the Order of the Phoenix (Har...,total:2358637,1,9,Scholastic Inc.,29770,2004,eng,J.K. Rowling,4.50,0439358078,870
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,total:6587388,1,11,Scholastic Inc,75911,2003,eng,J.K. Rowling,4.47,NaN,309
3,4,Harry Potter and the Chamber of Secrets (Harry...,total:2560657,1,11,Scholastic,244,2003,eng,J.K. Rowling,4.42,0439554896,352
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,total:2610317,1,5,Scholastic Inc.,37093,2004,eng,J.K. Rowling,4.57,043965548X,435

In [20]:
df = pd.read_csv("book_adaptation_df_clean.csv")
df

,movie_title,imdb_id,movie_budget,movie_revenue,movie_release,join_title,book_publisher,book_pages,book_rating,book_ratings_count,join_author,imdb_rating,imdb_total_votes
0,Toy Story,tt0114709,6.465807e+07,8.051095e+08,1995.0,toy story,NaN,0,0.0,0,NaN,8.3,1146884.0
1,Jumanji,tt0113497,1.400925e+08,5.663988e+08,1995.0,jumanji,NaN,0,0.0,0,NaN,7.1,404354.0
2,Grumpier Old Men,tt0113228,0.000000e+00,0.000000e+00,1995.0,grumpier old men,NaN,0,0.0,0,NaN,6.7,31161.0
3,Waiting to Exhale,tt0114885,3.448431e+07,1.755513e+08,1995.0,waiting to exhale,NaN,0,0.0,0,NaN,6.0,13134.0
4,Father of the Bride Part II,tt0113041,0.000000e+00,1.650482e+08,1995.0,father of the bride part ii,NaN,0,0.0,0,NaN,6.1,44260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,Subdue,tt6209470,0.000000e+00,0.000000e+00,0.0,subdue,NaN,0,0.0,0,NaN,6.1,2652.0
45462,Century of Birthing,tt2028550,0.000000e+00,0.000000e+00,2011.0,century of birthing,NaN,0,0.0,0,NaN,7.4,344.0
45463,Betrayal,tt0303758,0.000000e+00,0.000000e+00,2003.0,betrayal,NaN,0,0.0,0,NaN,4.3,1128.0
45464,Satan Triumphant,tt0008536,0.000000e+00,0.000000e+00,1917.0,satan triumphant,NaN,0,0.0,0,NaN,6.7,260.0
45465,Queerama,tt6980792,0.000000e+00,0.000000e+00,2017.0,queerama,NaN,0,0.0,0,NaN,6.3,239.0

In [12]:
df1 = pd.read_csv("book1-100k.csv")
df1["Pages"] = df1["pagesNumber"]
df_books = df1.drop(['RatingDist1', 'RatingDist2', 'RatingDist3', 'RatingDist4', 'RatingDist5', "pagesNumber"], axis=1)
df_books["Name"] = df_books["Name"].str.lower()
df_books.head(1)

,Id,Name,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,ISBN,Pages
0,1,harry potter and the half-blood prince (harry ...,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,NaN,652

In [17]:
filtered_df_books = df_books[df_books["Name"].isin(df["join_title"])]
filtered_df_books

,Id,Name,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,ISBN,Pages
39,61,the changeling,total:1365,8,6,iUniverse,97,2004,eng,Zilpha Keatley Snyder,4.17,0595321801,228
102,151,anna karenina,total:631550,31,5,Penguin Classics,1873,2004,eng,Leo Tolstoy,4.05,0143035002,838
108,164,the untouchables,total:684,1,2,Buccaneer Books,31,1996,eng,Eliot Ness,3.89,1568491980,256
133,218,the woman chaser,total:600,1,4,Newstand Library,51,1960,NaN,Charles Willeford,3.93,1842430017,192
139,228,cockfighter,total:1200,1,6,Blackmask.com,62,2005,NaN,Charles Willeford,4.11,1596542225,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58145,99791,golem,total:3645,18,10,Clarion Books,428,1996,eng,David Wisniewski,3.73,0395726182,32
58148,99794,the golem,total:5521,28,6,Dedalus,174,2000,eng,Gustav Meyrink,3.88,1873982917,264
58154,99809,the earthquake,total:98,1,5,Saqi Books,3,2000,NaN,Tahir Wattar,2.95,0863563392,184
58215,99894,the boys from brazil,total:33560,12,2,Random House,570,1976,eng,Ira Levin,4.06,0394402677,312
58245,99935,power,total:384,1,11,New York University Press,0,1986,NaN,Cherryl Walker,3.89,0814750303,283

In [ ]:
filtered_df_books.columns

Index(['Id', 'Name', 'RatingDistTotal', 'PublishMonth', 'PublishDay',
       'Publisher', 'CountsOfReview', 'PublishYear', 'Language', 'Authors',
       'Rating', 'ISBN', 'Pages'],
      dtype='object')

In [23]:
df.columns

Index(['movie_title', 'imdb_id', 'movie_budget', 'movie_revenue',
       'movie_release', 'join_title', 'book_publisher', 'book_pages',
       'book_rating', 'book_ratings_count', 'join_author', 'imdb_rating',
       'imdb_total_votes'],
      dtype='object')

In [28]:
df['join_title'] = df['join_title'].str.lower().str.strip()
filtered_df_books['Name'] = filtered_df_books['Name'].str.lower().str.strip()

C:\Users\khush\AppData\Local\Temp\ipykernel_18408\3762268249.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_books['Name'] = filtered_df_books['Name'].str.lower().str.strip()

In [32]:
# Clean the titles to make sure they match
df['join_title'] = df['join_title'].str.lower().str.strip()
filtered_df_books['Name'] = filtered_df_books['Name'].str.lower().str.strip()

# Keep only the rows in df where join_title is in the books database
df_books_only = df[df['join_title'].isin(filtered_df_books['Name'])].copy()

C:\Users\khush\AppData\Local\Temp\ipykernel_18408\279681092.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_books['Name'] = filtered_df_books['Name'].str.lower().str.strip()

In [31]:
merged_df = df.merge(
    filtered_df_books[['Name', 'Publisher', 'Pages', 'Rating', 'RatingDistTotal', 'Authors']],
    left_on='join_title',
    right_on='Name',
    how='left',
    suffixes=('', '_book')
)
print(merged_df.columns)
column_mapping = {
    'Publisher': 'book_publisher',
    'Pages': 'book_pages',
    'Rating': 'book_rating',
    'RatingDistTotal': 'book_ratings_count',
    'Authors': 'join_author'
}
for book_col, df_col in column_mapping.items():
    book_col_name = f'{book_col}_book'
    if book_col_name in merged_df.columns:
        merged_df[df_col] = merged_df[df_col].combine_first(merged_df[book_col_name])
merged_df = merged_df.drop(columns=[c for c in merged_df.columns if c.endswith('_book')] + ["Name"])
merged_df

Index(['movie_title', 'imdb_id', 'movie_budget', 'movie_revenue',
       'movie_release', 'join_title', 'book_publisher', 'book_pages',
       'book_rating', 'book_ratings_count', 'join_author', 'imdb_rating',
       'imdb_total_votes', 'Name', 'Publisher', 'Pages', 'Rating',
       'RatingDistTotal', 'Authors'],
      dtype='object')

,movie_title,imdb_id,movie_budget,movie_revenue,movie_release,join_title,book_publisher,book_pages,book_rating,book_ratings_count,join_author,imdb_rating,imdb_total_votes,Publisher,Pages,Rating,RatingDistTotal,Authors
0,Toy Story,tt0114709,6.465807e+07,8.051095e+08,1995.0,toy story,NaN,0,0.0,0,NaN,8.3,1146884.0,NaN,NaN,NaN,NaN,NaN
1,Jumanji,tt0113497,1.400925e+08,5.663988e+08,1995.0,jumanji,NaN,0,0.0,0,NaN,7.1,404354.0,Scholastic,48.0,4.07,total:28,A.L. Singer
2,Grumpier Old Men,tt0113228,0.000000e+00,0.000000e+00,1995.0,grumpier old men,NaN,0,0.0,0,NaN,6.7,31161.0,NaN,NaN,NaN,NaN,NaN
3,Waiting to Exhale,tt0114885,3.448431e+07,1.755513e+08,1995.0,waiting to exhale,NaN,0,0.0,0,NaN,6.0,13134.0,NaN,NaN,NaN,NaN,NaN
4,Father of the Bride Part II,tt0113041,0.000000e+00,1.650482e+08,1995.0,father of the bride part ii,NaN,0,0.0,0,NaN,6.1,44260.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45882,Subdue,tt6209470,0.000000e+00,0.000000e+00,0.0,subdue,NaN,0,0.0,0,NaN,6.1,2652.0,NaN,NaN,NaN,NaN,NaN
45883,Century of Birthing,tt2028550,0.000000e+00,0.000000e+00,2011.0,century of birthing,NaN,0,0.0,0,NaN,7.4,344.0,NaN,NaN,NaN,NaN,NaN
45884,Betrayal,tt0303758,0.000000e+00,0.000000e+00,2003.0,betrayal,NaN,0,0.0,0,NaN,4.3,1128.0,NaN,NaN,NaN,NaN,NaN
45885,Satan Triumphant,tt0008536,0.000000e+00,0.000000e+00,1917.0,satan triumphant,NaN,0,0.0,0,NaN,6.7,260.0,NaN,NaN,NaN,NaN,NaN
45886,Queerama,tt6980792,0.000000e+00,0.000000e+00,2017.0,queerama,NaN,0,0.0,0,NaN,6.3,239.0,NaN,NaN,NaN,NaN,NaN

In [34]:
merged_df = df_books_only.merge(
    filtered_df_books[['Name', 'Publisher', 'Pages', 'Rating', 'RatingDistTotal', 'Authors']],
    left_on='join_title',
    right_on='Name',
    how='left',
    suffixes=('', '_book')
)

column_mapping = {
    'Publisher': 'book_publisher',
    'Pages': 'book_pages',
    'Rating': 'book_rating',
    'RatingDistTotal': 'book_ratings_count',
    'Authors': 'join_author'
}

for book_col, df_col in column_mapping.items():
    book_col_name = f'{book_col}_book'
    if book_col_name in merged_df.columns:
        merged_df[df_col] = merged_df[df_col].combine_first(merged_df[book_col_name])

merged_df = merged_df.drop(columns=[c for c in merged_df.columns if c.endswith('_book')] + ['Name'])
df = merged_df  # now df contains only books with filled info
df

,movie_title,imdb_id,movie_budget,movie_revenue,movie_release,join_title,book_publisher,book_pages,book_rating,book_ratings_count,join_author,imdb_rating,imdb_total_votes,Publisher,Pages,Rating,RatingDistTotal,Authors
0,Jumanji,tt0113497,1.400925e+08,5.663988e+08,1995.0,jumanji,NaN,0,0.0,0,NaN,7.1,404354.0,Scholastic,48,4.07,total:28,A.L. Singer
1,Heat,tt0113277,1.293161e+08,4.039768e+08,1995.0,heat,NaN,0,0.0,0,NaN,8.3,779065.0,Philomel Books,220,3.98,total:19350,Mike Lupica
2,Heat,tt0113277,1.293161e+08,4.039768e+08,1995.0,heat,NaN,0,0.0,0,NaN,8.3,779065.0,iUniverse,256,3.45,total:73,Arthur Herzog III
3,Sense and Sensibility,tt0114388,3.556194e+07,2.909613e+08,1995.0,sense and sensibility,NaN,0,0.0,0,NaN,7.7,134114.0,"Oxford University Press, USA",446,4.07,total:917623,Jane Austen
4,Sense and Sensibility,tt0114388,3.556194e+07,2.909613e+08,1995.0,sense and sensibility,NaN,0,0.0,0,NaN,7.7,134114.0,AudioGO,0,4.07,total:917839,Jane Austen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3260,Twelve Angry Men,tt0122737,0.000000e+00,0.000000e+00,1954.0,twelve angry men,NaN,0,0.0,0,NaN,7.5,421.0,Penguin Classics,73,4.09,total:22565,Reginald Rose
3261,Mars,tt0417949,3.482211e+06,0.000000e+00,2004.0,mars,NaN,0,0.0,0,NaN,6.1,321.0,"Collector's Guide Publishing, Inc.",96,2.00,total:1,Robert Godwin
3262,Savages,tt0933361,1.302029e+06,2.162364e+06,2006.0,savages,NaN,0,0.0,0,NaN,6.4,731.0,Random House Value Publishing,0,4.06,total:671,Joe Kane
3263,The Hunters,tt0392137,0.000000e+00,0.000000e+00,1957.0,the hunters,NaN,0,0.0,0,NaN,7.0,124.0,Picador,200,3.42,total:513,Claire Messud
3264,Robin Hood,tt0102797,0.000000e+00,0.000000e+00,1991.0,robin hood,NaN,0,0.0,0,NaN,5.7,6256.0,Atheneum Books for Young Readers,64,4.00,total:1329,Paul Creswick

In [36]:
df = df.drop(columns=['book_publisher', 'book_pages', 'book_ratings_count', 'book_rating', 'join_author'])
df

,movie_title,imdb_id,movie_budget,movie_revenue,movie_release,join_title,imdb_rating,imdb_total_votes,Publisher,Pages,Rating,RatingDistTotal,Authors
0,Jumanji,tt0113497,1.400925e+08,5.663988e+08,1995.0,jumanji,7.1,404354.0,Scholastic,48,4.07,total:28,A.L. Singer
1,Heat,tt0113277,1.293161e+08,4.039768e+08,1995.0,heat,8.3,779065.0,Philomel Books,220,3.98,total:19350,Mike Lupica
2,Heat,tt0113277,1.293161e+08,4.039768e+08,1995.0,heat,8.3,779065.0,iUniverse,256,3.45,total:73,Arthur Herzog III
3,Sense and Sensibility,tt0114388,3.556194e+07,2.909613e+08,1995.0,sense and sensibility,7.7,134114.0,"Oxford University Press, USA",446,4.07,total:917623,Jane Austen
4,Sense and Sensibility,tt0114388,3.556194e+07,2.909613e+08,1995.0,sense and sensibility,7.7,134114.0,AudioGO,0,4.07,total:917839,Jane Austen
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3260,Twelve Angry Men,tt0122737,0.000000e+00,0.000000e+00,1954.0,twelve angry men,7.5,421.0,Penguin Classics,73,4.09,total:22565,Reginald Rose
3261,Mars,tt0417949,3.482211e+06,0.000000e+00,2004.0,mars,6.1,321.0,"Collector's Guide Publishing, Inc.",96,2.00,total:1,Robert Godwin
3262,Savages,tt0933361,1.302029e+06,2.162364e+06,2006.0,savages,6.4,731.0,Random House Value Publishing,0,4.06,total:671,Joe Kane
3263,The Hunters,tt0392137,0.000000e+00,0.000000e+00,1957.0,the hunters,7.0,124.0,Picador,200,3.42,total:513,Claire Messud
3264,Robin Hood,tt0102797,0.000000e+00,0.000000e+00,1991.0,robin hood,5.7,6256.0,Atheneum Books for Young Readers,64,4.00,total:1329,Paul Creswick

In [37]:
df.to_csv('cleaned_df.csv')