In [1]:
import pandas as pd
df = pd.read_csv("book_adaptation_df_clean.csv")
df

,movie_title,imdb_id,movie_budget,movie_revenue,movie_release,join_title,book_publisher,book_pages,book_rating,book_ratings_count,join_author,imdb_rating,imdb_total_votes
0,Toy Story,tt0114709,6.465807e+07,8.051095e+08,1995.0,toy story,NaN,0,0.0,0,NaN,8.3,1146884.0
1,Jumanji,tt0113497,1.400925e+08,5.663988e+08,1995.0,jumanji,NaN,0,0.0,0,NaN,7.1,404354.0
2,Grumpier Old Men,tt0113228,0.000000e+00,0.000000e+00,1995.0,grumpier old men,NaN,0,0.0,0,NaN,6.7,31161.0
3,Waiting to Exhale,tt0114885,3.448431e+07,1.755513e+08,1995.0,waiting to exhale,NaN,0,0.0,0,NaN,6.0,13134.0
4,Father of the Bride Part II,tt0113041,0.000000e+00,1.650482e+08,1995.0,father of the bride part ii,NaN,0,0.0,0,NaN,6.1,44260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,Subdue,tt6209470,0.000000e+00,0.000000e+00,0.0,subdue,NaN,0,0.0,0,NaN,6.1,2652.0
45462,Century of Birthing,tt2028550,0.000000e+00,0.000000e+00,2011.0,century of birthing,NaN,0,0.0,0,NaN,7.4,344.0
45463,Betrayal,tt0303758,0.000000e+00,0.000000e+00,2003.0,betrayal,NaN,0,0.0,0,NaN,4.3,1128.0
45464,Satan Triumphant,tt0008536,0.000000e+00,0.000000e+00,1917.0,satan triumphant,NaN,0,0.0,0,NaN,6.7,260.0
45465,Queerama,tt6980792,0.000000e+00,0.000000e+00,2017.0,queerama,NaN,0,0.0,0,NaN,6.3,239.0

In [2]:
df_hasData = df[df["imdb_rating"] != 0]
df_hasData

,movie_title,imdb_id,movie_budget,movie_revenue,movie_release,join_title,book_publisher,book_pages,book_rating,book_ratings_count,join_author,imdb_rating,imdb_total_votes
0,Toy Story,tt0114709,6.465807e+07,8.051095e+08,1995.0,toy story,NaN,0,0.0,0,NaN,8.3,1146884.0
1,Jumanji,tt0113497,1.400925e+08,5.663988e+08,1995.0,jumanji,NaN,0,0.0,0,NaN,7.1,404354.0
2,Grumpier Old Men,tt0113228,0.000000e+00,0.000000e+00,1995.0,grumpier old men,NaN,0,0.0,0,NaN,6.7,31161.0
3,Waiting to Exhale,tt0114885,3.448431e+07,1.755513e+08,1995.0,waiting to exhale,NaN,0,0.0,0,NaN,6.0,13134.0
4,Father of the Bride Part II,tt0113041,0.000000e+00,1.650482e+08,1995.0,father of the bride part ii,NaN,0,0.0,0,NaN,6.1,44260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,Subdue,tt6209470,0.000000e+00,0.000000e+00,0.0,subdue,NaN,0,0.0,0,NaN,6.1,2652.0
45462,Century of Birthing,tt2028550,0.000000e+00,0.000000e+00,2011.0,century of birthing,NaN,0,0.0,0,NaN,7.4,344.0
45463,Betrayal,tt0303758,0.000000e+00,0.000000e+00,2003.0,betrayal,NaN,0,0.0,0,NaN,4.3,1128.0
45464,Satan Triumphant,tt0008536,0.000000e+00,0.000000e+00,1917.0,satan triumphant,NaN,0,0.0,0,NaN,6.7,260.0
45465,Queerama,tt6980792,0.000000e+00,0.000000e+00,2017.0,queerama,NaN,0,0.0,0,NaN,6.3,239.0