In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression

In [44]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [45]:
df = pd.read_csv("final_data.csv")
df

,Unnamed: 0,movie_title,movie_budget,movie_revenue,movie_release,imdb_total_votes,Publisher,Pages,RatingDistTotal,Authors,Book Rating,Movie Rating,movie_profit
0,0,Jumanji,1.400925e+08,5.663988e+08,1995.0,404354.0,Scholastic,48.0,28,A.L. Singer,0.814,0.71,4.263063e+08
1,1,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,Philomel Books,220.0,19350,Mike Lupica,0.796,0.83,2.746606e+08
2,2,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,iUniverse,256.0,73,Arthur Herzog III,0.690,0.83,2.746606e+08
3,3,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,"Oxford University Press, USA",446.0,917623,Jane Austen,0.814,0.77,2.553994e+08
4,4,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,AudioGO,NaN,917839,Jane Austen,0.814,0.77,2.553994e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3260,3260,Twelve Angry Men,NaN,NaN,1954.0,421.0,Penguin Classics,73.0,22565,Reginald Rose,0.818,0.75,NaN
3261,3261,Mars,3.482211e+06,NaN,2004.0,321.0,"Collector's Guide Publishing, Inc.",96.0,1,Robert Godwin,0.400,0.61,NaN
3262,3262,Savages,1.302029e+06,2.162364e+06,2006.0,731.0,Random House Value Publishing,NaN,671,Joe Kane,0.812,0.64,8.603353e+05
3263,3263,The Hunters,NaN,NaN,1957.0,124.0,Picador,200.0,513,Claire Messud,0.684,0.70,NaN
3264,3264,Robin Hood,NaN,NaN,1991.0,6256.0,Atheneum Books for Young Readers,64.0,1329,Paul Creswick,0.800,0.57,NaN

In [46]:
# Remove the unnamed column if it exists
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)
df.head()

,movie_title,movie_budget,movie_revenue,movie_release,imdb_total_votes,Publisher,Pages,RatingDistTotal,Authors,Book Rating,Movie Rating,movie_profit
0,Jumanji,1.400925e+08,5.663988e+08,1995.0,404354.0,Scholastic,48.0,28,A.L. Singer,0.814,0.71,4.263063e+08
1,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,Philomel Books,220.0,19350,Mike Lupica,0.796,0.83,2.746606e+08
2,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,iUniverse,256.0,73,Arthur Herzog III,0.690,0.83,2.746606e+08
3,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,"Oxford University Press, USA",446.0,917623,Jane Austen,0.814,0.77,2.553994e+08
4,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,AudioGO,NaN,917839,Jane Austen,0.814,0.77,2.553994e+08

In [47]:
df = df.dropna(subset=['Book Rating', 'Movie Rating'])

In [48]:
model = LinearRegression()
ind = ["Book Rating"]
dep = "Movie Rating"
model.fit(df[ind], df[dep])
df["Movie Rating Prediction"] = model.predict(df[ind])
df

,movie_title,movie_budget,movie_revenue,movie_release,imdb_total_votes,Publisher,Pages,RatingDistTotal,Authors,Book Rating,Movie Rating,movie_profit,Movie Rating Prediction
0,Jumanji,1.400925e+08,5.663988e+08,1995.0,404354.0,Scholastic,48.0,28,A.L. Singer,0.814,0.71,4.263063e+08,0.665608
1,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,Philomel Books,220.0,19350,Mike Lupica,0.796,0.83,2.746606e+08,0.659898
2,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,iUniverse,256.0,73,Arthur Herzog III,0.690,0.83,2.746606e+08,0.626267
3,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,"Oxford University Press, USA",446.0,917623,Jane Austen,0.814,0.77,2.553994e+08,0.665608
4,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,AudioGO,NaN,917839,Jane Austen,0.814,0.77,2.553994e+08,0.665608
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3260,Twelve Angry Men,NaN,NaN,1954.0,421.0,Penguin Classics,73.0,22565,Reginald Rose,0.818,0.75,NaN,0.666878
3261,Mars,3.482211e+06,NaN,2004.0,321.0,"Collector's Guide Publishing, Inc.",96.0,1,Robert Godwin,0.400,0.61,NaN,0.534257
3262,Savages,1.302029e+06,2.162364e+06,2006.0,731.0,Random House Value Publishing,NaN,671,Joe Kane,0.812,0.64,8.603353e+05,0.664974
3263,The Hunters,NaN,NaN,1957.0,124.0,Picador,200.0,513,Claire Messud,0.684,0.70,NaN,0.624363
3264,Robin Hood,NaN,NaN,1991.0,6256.0,Atheneum Books for Young Readers,64.0,1329,Paul Creswick,0.800,0.57,NaN,0.661167

In [49]:
df["Movie Rating Residual"] = df["Movie Rating"] - df["Movie Rating Prediction"]
df.head()

,movie_title,movie_budget,movie_revenue,movie_release,imdb_total_votes,Publisher,Pages,RatingDistTotal,Authors,Book Rating,Movie Rating,movie_profit,Movie Rating Prediction,Movie Rating Residual
0,Jumanji,1.400925e+08,5.663988e+08,1995.0,404354.0,Scholastic,48.0,28,A.L. Singer,0.814,0.71,4.263063e+08,0.665608,0.044392
1,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,Philomel Books,220.0,19350,Mike Lupica,0.796,0.83,2.746606e+08,0.659898,0.170102
2,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,iUniverse,256.0,73,Arthur Herzog III,0.690,0.83,2.746606e+08,0.626267,0.203733
3,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,"Oxford University Press, USA",446.0,917623,Jane Austen,0.814,0.77,2.553994e+08,0.665608,0.104392
4,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,AudioGO,NaN,917839,Jane Austen,0.814,0.77,2.553994e+08,0.665608,0.104392

<p>Linear Regression predicts Movie Rating very well based on Book Rating.</p>

In [6]:
df = pd.read_csv("final_data.csv")
# Remove the unnamed column if it exists
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)
df = df.fillna(0)
df.head()

,movie_title,movie_budget,movie_revenue,movie_release,imdb_total_votes,Publisher,Pages,RatingDistTotal,Authors,Book Rating,Movie Rating,movie_profit
0,Jumanji,1.400925e+08,5.663988e+08,1995.0,404354.0,Scholastic,48.0,28,A.L. Singer,0.814,0.71,4.263063e+08
1,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,Philomel Books,220.0,19350,Mike Lupica,0.796,0.83,2.746606e+08
2,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,iUniverse,256.0,73,Arthur Herzog III,0.690,0.83,2.746606e+08
3,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,"Oxford University Press, USA",446.0,917623,Jane Austen,0.814,0.77,2.553994e+08
4,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,AudioGO,0.0,917839,Jane Austen,0.814,0.77,2.553994e+08

In [7]:
model = LinearRegression()

ind = ["Book Rating"]
dep = "movie_revenue"
model.fit(df[ind], df[dep])

df["Movie Rev Prediction"] = model.predict(df[ind])
df["Movie Rev Residual"] = df["movie_revenue"] - df["Movie Rev Prediction"]
df.head()

,movie_title,movie_budget,movie_revenue,movie_release,imdb_total_votes,Publisher,Pages,RatingDistTotal,Authors,Book Rating,Movie Rating,movie_profit,Movie Rev Prediction,Movie Rev Residual
0,Jumanji,1.400925e+08,5.663988e+08,1995.0,404354.0,Scholastic,48.0,28,A.L. Singer,0.814,0.71,4.263063e+08,5.564302e+07,5.107558e+08
1,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,Philomel Books,220.0,19350,Mike Lupica,0.796,0.83,2.746606e+08,5.289216e+07,3.510846e+08
2,Heat,1.293161e+08,4.039768e+08,1995.0,779065.0,iUniverse,256.0,73,Arthur Herzog III,0.690,0.83,2.746606e+08,3.669266e+07,3.672841e+08
3,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,"Oxford University Press, USA",446.0,917623,Jane Austen,0.814,0.77,2.553994e+08,5.564302e+07,2.353183e+08
4,Sense and Sensibility,3.556194e+07,2.909613e+08,1995.0,134114.0,AudioGO,0.0,917839,Jane Austen,0.814,0.77,2.553994e+08,5.564302e+07,2.353183e+08

<p>Linear Regression doesn't do a good job at predicting Movie Revenue based on book rating. This is clear in the residual since it is super high</p>